name: My First Workflow 

on: [push] 

jobs: 
    first_job: 
        runs-on: ubuntu-latest 
        steps: # Steps will run in series 
        - name: Welcome message 
          run: echo "My First Github Action" 

        - name: List files 
          run: ls -lthr 

        - name: Read file 
          run: cat hello-world.txt 
