name: Generate ASCII Artwork 

on: push 

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest 
        
        steps: 
            - name: Checkout Repo 
              uses: actions/checkout@v4 

            - name: Install Cowsay 
              run: sudo apt-get install cowsay -y 

            - name: Execute cowsay command 
              run: cowsay -f dragon "run for cover" >> dragon.txt 

            - name: Read file 
              run: cat dragon.txt 

            - name: Checkout Repo Files 
              run: ls 