name: Generate ASCII Artwork 

on: push 

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest 
        
        steps: 
            - name: Checkout Repo 
              uses: actions/checkout@v4 

            - name: Validate YAML file
              run: yamllint generate-ascii.yml

            - name: Execute Shell Script 
              run: ./ascii-script.sh 

