name: Matrix Configuration 

on: 
    push: 
    workflow_dispatch: 

jobs: 
    deploy: 
        strategy: 
            fail-fast: false # Prevents 1 failure from cancelling the other jobs 
            max-parallel: 2 # Runs 2 jobs at a time
            matrix: # For a matrix, all possible combinations will be run. Hence, this matrix deploy job will have 6 
                    # different instances
                os: [ubuntu-latest, ubuntu-20.04]
                images: [hello-world, alpine]
                exckude: 
                    - images: alpine 
                      os: ubuntu-20.04
                include: 
                    - images: amd64/alpine 
                      os: ubuntu-20.04
        runs-on: ubuntu-latest
        steps: 
        - name: Echo docker 
          run: docker info 
        - name: Run image on ${{ matrix.os }}
          run: echo docker run ${{ matrix.images }}

    deploy-on-ubuntu: 
        runs-on: ubuntu-latest 
        steps: 
        - name: Echo docker details # Docker runs pre-installed on all GitHub provided images/runners 
          run: docker info 
        
        - name: Run images 
          run: echo docker run hello-world 

    deploy-on-windows: 
        runs-on: windows-latest 
        steps: 
        - name: Echo docker details 
          run: docker info 

        - name: Run images 
          run: echo docker run hello-world 