name: Tag release

on: 
    push: 
        tags: 
            - ^v\d+(\.\d+){2}$

env: 
    USERNAME: DOCKER_USERNAME_01

jobs: 
    
    docker_job: 
        env: 
            IMAGE_NAME: TEST_IMAGE_01
        runs-on: ubuntu-latest 
        steps: 
        - name: Starting tagged release process 
          run: echo releasing tag 
          env: 
            IMAGE_TAG: v0.0.1

