name: Tag release

on: 
    push: 
        tags: 
            - 'v*.*.*'

env: 
    USERNAME: DOCKER_USERNAME_01

jobs: 
    
    tag_release_job: 
        runs-on: ubuntu-latest 
        steps: 
        - name: Starting tagged release process 
          run: echo releasing tag 


