name: Tag release

on: 
    push: 
        tags: 
            - 'v*.*.*'

env: 
    USERNAME: DOCKER_USERNAME_01

jobs: 
    
    tag_release_job: 
        runs-on: ubuntu-latest 
        steps: 
 
        - name: Obtain tag version
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Echo GitHub context 
          run: echo "$GITHUB_CONTEXT"
        
        - name: Starting tagged release process for release version
          run: echo "Release version is $RELEASE_VERSION"


