name: Exploring variables & secrets 

on: 
    push 

env: 
    USERNAME: DOCKER_USERNAME_01

jobs: 
    
    docker_job: 
        env: 
            IMAGE_NAME: TEST_IMAGE_01
        runs-on: ubuntu-latest 
        steps: 
        - name: Docker build 
          run: echo docker build -t docker.io/$USERNAME/${{ env.IMAGE_NAME}}:$IMAGE_TAG --password=${{ secrets.DOCKER_PASSWORD }} --env=${{ env.REPO_VAR_01 }}
          env: 
            IMAGE_TAG: v0.0.1

